//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoQuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoQuan()
        {
            this.VanBanDis = new HashSet<VanBanDi>();
            this.VanBanDenHuyens = new HashSet<VanBanDenHuyen>();
            this.VanBanDenTinhs = new HashSet<VanBanDenTinh>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Huyen { get; set; }
        public Nullable<int> Tinh { get; set; }
        public Nullable<int> Xa { get; set; }
        public Nullable<int> Khac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanBanDi> VanBanDis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanBanDenHuyen> VanBanDenHuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanBanDenTinh> VanBanDenTinhs { get; set; }
    }
}
