//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOffice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOfficeEntities : DbContext
    {
        public MOfficeEntities()
            : base("name=MOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoQuan> CoQuans { get; set; }
        public virtual DbSet<LoaiVanBan> LoaiVanBans { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<VanBanDi> VanBanDis { get; set; }
        public virtual DbSet<VanBanDenHuyen> VanBanDenHuyens { get; set; }
        public virtual DbSet<VanBanDenTinh> VanBanDenTinhs { get; set; }
        public virtual DbSet<LoaiTrichYeu> LoaiTrichYeus { get; set; }
        public virtual DbSet<CanBo> CanBoes { get; set; }
    }
}
